### ISSUE TITLE
Rename DisableThrottingAttribute 

### ISSUE THREAD

**Issue by natelowry** [stefanprodan/MvcThrottle#13]
Missing an l  😺 

`DisableThrottingAttribute` => `DisableThrottlingAttribute` 
`DisableThrotting` => `DisableThrottling`

**Comment by natelowry** [comment]
Not trying to pick on your awesome project, just made it a little tough to find in the solution. 🔍

**Comment by stefanprodan** [comment]
Thanks for the heads up
