### ISSUE TITLE
DisableThrottling on Class

### ISSUE THREAD

**Issue by natelowry** [stefanprodan/MvcThrottle#14]
Me again 😺 

The `DisableThrottlingAttribute` is checked at the Action level, but not on the Class.  Is there a reason for this?  We have some base classes that have it enabled and want to disable it on specific inherited classes.  ~If not, maybe mark that attribute as `Method` only?~ _Edit: can't do that with `ActionFilterAttribute` apparently_

I think the fix would be to `ThrottlingFilter.cs:352` [here](https://github.com/stefanprodan/MvcThrottle/blob/master/MvcThrottle/ThrottlingFilter.cs#L352):

```
            if (filterContext.ActionDescriptor.ControllerDescriptor.IsDefined(typeof(DisableThrottlingAttribute), true))
            {
                applyThrottling = false;
            }
```

I'd be happy to PR that if it helps.  

We just pushed this into production and are much <3

**Comment by stefanprodan** [comment]
Please make a PR and I'll merge it. Thanks
