### ISSUE TITLE
Null user agent exceptions

### ISSUE THREAD

**Issue by patja** [stefanprodan/MvcThrottle#18]
With user agent throttling there is one more place where a null user agent check should be made to prevent null reference exceptions.

In ThrottlingFilter.cs:

```c#
//apply custom rate limit for user agent
if (Policy.UserAgentRules != null)
```

can be changed to:

```c#
//apply custom rate limit for user agent
if (Policy.UserAgentRules != null && identity.UserAgent != null)
```

to prevent the null reference exceptions

**Comment by stefanprodan** [comment]
v2.1.3 has been published to NuGet

Thanks
