### ISSUE TITLE
Requests always stacking

### ISSUE THREAD

**Issue by georgehemmings** [stefanprodan/MvcThrottle#4]
The readme describes the default stacking policy "If a client makes 3 requests per second and you've set a limit of one call per second, the minute, hour and day counters will only record the first call, the one that wasn't blocked."

This isn't the behaviour I'm seeing.

I think this commit may have broken this feature:  https://github.com/stefanprodan/MvcThrottle/commit/0f60a5af239f71df2d38466e35a50cb2ee77984c

As an exception is no longer thrown once a rate has been exceeded, it goes on to evaluate all the others rates also.

Should it just `return` after `filterContext.Result` is set?

**Comment by georgehemmings** [comment]
https://github.com/stefanprodan/MvcThrottle/pull/5

**Comment by stefanprodan** [comment]
Please update to v1.0.5, it's on NuGet.

**Comment by georgehemmings** [comment]
Thanks
